export const task = async <T, TR>(input: T, task: (input: T) => TR | Promise<TR>, then, failed, throwOnFail = true) => {
    try {

    } catch (error) {
        throw error;
    }
};